/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Audrey
 */
public class New_Patient extends javax.swing.JFrame {

    /** Creates new form Modif_Patient */
    public New_Patient() {
        initComponents();
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((screen.getWidth() - getWidth()) /2);
        int y = (int) ((screen.getHeight() -getHeight()) /2);
        setLocation(x, y); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Label_Nom = new javax.swing.JLabel();
        Label_Prenom = new javax.swing.JLabel();
        Label_Date_Naissance = new javax.swing.JLabel();
        Label_Adresse = new javax.swing.JLabel();
        Label_Ville = new javax.swing.JLabel();
        Label_Code_Postal = new javax.swing.JLabel();
        Label_Photo = new javax.swing.JLabel();
        Label_Commentaire = new javax.swing.JLabel();
        TextField_Adresse = new javax.swing.JTextField();
        TextField_Ville = new javax.swing.JTextField();
        TextField_Code_Postal = new javax.swing.JTextField();
        TextField_Photo = new javax.swing.JTextField();
        Button_Telecharger = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea_Commentaire = new javax.swing.JTextArea();
        Label_Sexe = new javax.swing.JLabel();
        TextField_Nom = new javax.swing.JTextField();
        jTextField_Prenom = new javax.swing.JTextField();
        TextField_Date = new javax.swing.JTextField();
        RadioButton_F = new javax.swing.JRadioButton();
        RadioButton_H = new javax.swing.JRadioButton();
        Button_Valider = new javax.swing.JButton();

        setTitle("Modifications");

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        Label_Nom.setText("Nom :");

        Label_Prenom.setText("Prénom :");

        Label_Date_Naissance.setText("Date de naissance :");

        Label_Adresse.setText("Adresse :");

        Label_Ville.setText("Ville :");

        Label_Code_Postal.setText("Code Postal :");

        Label_Photo.setText("Photo :");

        Label_Commentaire.setText("Commentaire :");

        TextField_Adresse.setText("X rue X");
        TextField_Adresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_AdresseActionPerformed(evt);
            }
        });

        TextField_Ville.setText("XXX");

        TextField_Code_Postal.setText("00000");
        TextField_Code_Postal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Code_PostalActionPerformed(evt);
            }
        });

        TextField_Photo.setText("URL");
        TextField_Photo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_PhotoActionPerformed(evt);
            }
        });

        Button_Telecharger.setText("Télécharger");
        Button_Telecharger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TelechargerActionPerformed(evt);
            }
        });

        TextArea_Commentaire.setColumns(20);
        TextArea_Commentaire.setRows(5);
        jScrollPane1.setViewportView(TextArea_Commentaire);

        Label_Sexe.setText("Sexe :");

        TextField_Nom.setText("jTextField1");

        jTextField_Prenom.setText("jTextField2");

        TextField_Date.setText("jTextField3");

        RadioButton_F.setText("F");
        RadioButton_F.setBorder(null);
        RadioButton_F.setOpaque(false);
        RadioButton_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton_FActionPerformed(evt);
            }
        });

        RadioButton_H.setText("H");
        RadioButton_H.setBorder(null);
        RadioButton_H.setOpaque(false);

        Button_Valider.setBackground(new java.awt.Color(0, 204, 0));
        Button_Valider.setText("Valider");
        Button_Valider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_ValiderMouseClicked(evt);
            }
        });
        Button_Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ValiderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Label_Adresse)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextField_Adresse))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Label_Photo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextField_Photo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Button_Telecharger))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Label_Ville)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextField_Ville)
                                .addGap(18, 18, 18)
                                .addComponent(Label_Code_Postal)
                                .addGap(18, 18, 18)
                                .addComponent(TextField_Code_Postal))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Label_Commentaire)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Label_Date_Naissance)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextField_Date, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Label_Prenom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Prenom))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Label_Nom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextField_Nom)))
                        .addGap(113, 113, 113)
                        .addComponent(Label_Sexe)
                        .addGap(18, 18, 18)
                        .addComponent(RadioButton_F)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RadioButton_H)
                        .addGap(42, 42, 42))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_Valider)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Nom)
                    .addComponent(Label_Sexe)
                    .addComponent(TextField_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioButton_F)
                    .addComponent(RadioButton_H))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Prenom)
                    .addComponent(jTextField_Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Date_Naissance)
                    .addComponent(TextField_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Adresse)
                    .addComponent(TextField_Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Ville)
                    .addComponent(TextField_Ville, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Code_Postal)
                    .addComponent(TextField_Code_Postal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Photo)
                    .addComponent(TextField_Photo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Telecharger))
                .addGap(18, 18, 18)
                .addComponent(Label_Commentaire)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Button_Valider)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_AdresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_AdresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_AdresseActionPerformed

    private void TextField_Code_PostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Code_PostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_Code_PostalActionPerformed

    private void Button_TelechargerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TelechargerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_TelechargerActionPerformed

    private void TextField_PhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_PhotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_PhotoActionPerformed

    private void RadioButton_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton_FActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton_FActionPerformed

    private void Button_ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ValiderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_ValiderActionPerformed

    private void Button_ValiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_ValiderMouseClicked
    dispose();
    }//GEN-LAST:event_Button_ValiderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Telecharger;
    private javax.swing.JButton Button_Valider;
    private javax.swing.JLabel Label_Adresse;
    private javax.swing.JLabel Label_Code_Postal;
    private javax.swing.JLabel Label_Commentaire;
    private javax.swing.JLabel Label_Date_Naissance;
    private javax.swing.JLabel Label_Nom;
    private javax.swing.JLabel Label_Photo;
    private javax.swing.JLabel Label_Prenom;
    private javax.swing.JLabel Label_Sexe;
    private javax.swing.JLabel Label_Ville;
    private javax.swing.JRadioButton RadioButton_F;
    private javax.swing.JRadioButton RadioButton_H;
    private javax.swing.JTextArea TextArea_Commentaire;
    private javax.swing.JTextField TextField_Adresse;
    private javax.swing.JTextField TextField_Code_Postal;
    private javax.swing.JTextField TextField_Date;
    private javax.swing.JTextField TextField_Nom;
    private javax.swing.JTextField TextField_Photo;
    private javax.swing.JTextField TextField_Ville;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_Prenom;
    // End of variables declaration//GEN-END:variables

}
