/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Audrey
 */
public class RDV_Med extends javax.swing.JFrame {

    /** Creates new form Historique_Prochains_RDV */
    public RDV_Med() {
        initComponents();
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((screen.getWidth() - getWidth()) /2);
        int y = (int) ((screen.getHeight() -getHeight()) /2);
        setLocation(x, y); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Button_RDV1 = new javax.swing.JButton();
        Label_Nom_Patient = new javax.swing.JLabel();
        Button_RDV2 = new javax.swing.JButton();
        TextField_Mois_Annee = new javax.swing.JTextField();
        TextField_Docteur = new javax.swing.JTextField();
        Label_Loupe_Date = new javax.swing.JLabel();
        Label_Loupe_Docteur = new javax.swing.JLabel();
        Panel_Fleche_G = new javax.swing.JPanel();
        Label_Fleche_G = new javax.swing.JLabel();
        Panel_Fleche_D = new javax.swing.JPanel();
        Label_Fleche_D = new javax.swing.JLabel();
        Pannel_RDV_Modif = new javax.swing.JPanel();
        Button_RDV3 = new javax.swing.JButton();
        Label_Trash = new javax.swing.JLabel();
        Label_Print = new javax.swing.JLabel();

        setLocation(location());
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        Button_RDV1.setText("RDV 1");
        Button_RDV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RDV1ActionPerformed(evt);
            }
        });

        Label_Nom_Patient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_Nom_Patient.setText("Nom Patient");

        Button_RDV2.setBackground(new java.awt.Color(0, 204, 0));
        Button_RDV2.setText("RDV 2");
        Button_RDV2.setToolTipText("");

        TextField_Mois_Annee.setText("Mois / Année");

        TextField_Docteur.setText("Docteur");
        TextField_Docteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_DocteurActionPerformed(evt);
            }
        });

        Label_Loupe_Date.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/loupe.png"))); // NOI18N

        Label_Loupe_Docteur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/loupe.png"))); // NOI18N

        Panel_Fleche_G.setOpaque(false);

        Label_Fleche_G.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fleche_gauche.png"))); // NOI18N

        javax.swing.GroupLayout Panel_Fleche_GLayout = new javax.swing.GroupLayout(Panel_Fleche_G);
        Panel_Fleche_G.setLayout(Panel_Fleche_GLayout);
        Panel_Fleche_GLayout.setHorizontalGroup(
            Panel_Fleche_GLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Fleche_GLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label_Fleche_G)
                .addContainerGap())
        );
        Panel_Fleche_GLayout.setVerticalGroup(
            Panel_Fleche_GLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Fleche_GLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(Label_Fleche_G)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        Panel_Fleche_D.setOpaque(false);

        Label_Fleche_D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fleche_droite.png"))); // NOI18N

        javax.swing.GroupLayout Panel_Fleche_DLayout = new javax.swing.GroupLayout(Panel_Fleche_D);
        Panel_Fleche_D.setLayout(Panel_Fleche_DLayout);
        Panel_Fleche_DLayout.setHorizontalGroup(
            Panel_Fleche_DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Fleche_DLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Fleche_D)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_Fleche_DLayout.setVerticalGroup(
            Panel_Fleche_DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Fleche_DLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(Label_Fleche_D)
                .addGap(46, 46, 46))
        );

        Pannel_RDV_Modif.setOpaque(false);

        Button_RDV3.setBackground(new java.awt.Color(255, 153, 51));
        Button_RDV3.setText("RDV 3");
        Button_RDV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RDV3ActionPerformed(evt);
            }
        });

        Label_Trash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/trash.png"))); // NOI18N

        Label_Print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/printer.png"))); // NOI18N

        javax.swing.GroupLayout Pannel_RDV_ModifLayout = new javax.swing.GroupLayout(Pannel_RDV_Modif);
        Pannel_RDV_Modif.setLayout(Pannel_RDV_ModifLayout);
        Pannel_RDV_ModifLayout.setHorizontalGroup(
            Pannel_RDV_ModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pannel_RDV_ModifLayout.createSequentialGroup()
                .addGroup(Pannel_RDV_ModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pannel_RDV_ModifLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Button_RDV3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pannel_RDV_ModifLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(Label_Trash)
                        .addGap(18, 18, 18)
                        .addComponent(Label_Print)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Pannel_RDV_ModifLayout.setVerticalGroup(
            Pannel_RDV_ModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pannel_RDV_ModifLayout.createSequentialGroup()
                .addComponent(Button_RDV3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Pannel_RDV_ModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Trash)
                    .addComponent(Label_Print))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TextField_Mois_Annee, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Label_Loupe_Date)
                                .addGap(80, 80, 80)
                                .addComponent(TextField_Docteur, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Label_Loupe_Docteur)
                                .addGap(114, 114, 114))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Panel_Fleche_G, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_RDV1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Button_RDV2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Pannel_RDV_Modif, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(Panel_Fleche_D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Label_Nom_Patient))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label_Nom_Patient)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField_Docteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Loupe_Date)
                    .addComponent(Label_Loupe_Docteur)
                    .addComponent(TextField_Mois_Annee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Panel_Fleche_G, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Panel_Fleche_D, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Button_RDV1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Button_RDV2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Pannel_RDV_Modif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_RDV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RDV3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_RDV3ActionPerformed

    private void TextField_DocteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_DocteurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_DocteurActionPerformed

    private void Button_RDV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RDV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_RDV1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RDV_Med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RDV_Med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RDV_Med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RDV_Med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RDV_Med().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_RDV1;
    private javax.swing.JButton Button_RDV2;
    private javax.swing.JButton Button_RDV3;
    private javax.swing.JLabel Label_Fleche_D;
    private javax.swing.JLabel Label_Fleche_G;
    private javax.swing.JLabel Label_Loupe_Date;
    private javax.swing.JLabel Label_Loupe_Docteur;
    private javax.swing.JLabel Label_Nom_Patient;
    private javax.swing.JLabel Label_Print;
    private javax.swing.JLabel Label_Trash;
    private javax.swing.JPanel Panel_Fleche_D;
    private javax.swing.JPanel Panel_Fleche_G;
    private javax.swing.JPanel Pannel_RDV_Modif;
    private javax.swing.JTextField TextField_Docteur;
    private javax.swing.JTextField TextField_Mois_Annee;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
