/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import nf.*;
import static nf.Checker.convertirDatetoString;
import java.time.LocalDate;
import java.time.LocalTime;

/**
 *
 * @author Audrey
 */
public class Vue_Patient_SA extends javax.swing.JFrame {

    SecretaireAdministrative sa;
    DPI dpi;
    Vector entetesL;
    Vector localisation;

    /**
     * Creates new form Connexion
     */
    public Vue_Patient_SA(DPI dpi, SecretaireAdministrative sa) {
        this.sa = sa;
        this.dpi = dpi;

        initComponents();

        //infos identité connexion
        prenom_SA.setText(sa.getNomSecretaireAd());
        nom_SA.setText(sa.getPrenomSecretaireAd());

        //infos du patient
        jLabel10.setText(dpi.getNom());
        jLabel11.setText(dpi.getPrenom());
        jLabel12.setText(dpi.getSexe().toString());
        String dN = convertirDatetoString(dpi.getDateNaissance());
        jLabel13.setText(dN);
        jLabel_telephone.setText(dpi.getTelephone());
        jLabel_adresse.setText(dpi.getAdresse());
        jLabel_medecin.setText(dpi.getMedecin_traitant().toString());

        //prochain rdv
        List<RendezVous> rdvsP = dpi.getdMA().getRendezVous();
        List<Evaluable> evs = new Vector<Evaluable>();
        evs.addAll(rdvsP);
        evs = nf.ComparaisonEvaluables.trierEvaluablesParDate(evs);
        RendezVous rdvP = (RendezVous) evs.get(0);
        jTextPane1.setText(rdvP.toStringProchainRDV());

        //jbutton
        ImageIcon icone1 = new ImageIcon("src/image/petit_crayon.png");
        java.awt.Image img1 = icone1.getImage();
        icone1 = new ImageIcon(img1);
        jButton_modifier.setIcon(icone1);
        jButton_modifier.setVerticalTextPosition(SwingConstants.BOTTOM);
        jButton_modifier.setHorizontalTextPosition(SwingConstants.CENTER);
        ImageIcon icone2 = new ImageIcon("src/image/fermer.png");
        java.awt.Image img2 = icone2.getImage();
        icone2 = new ImageIcon(img2);
        jButton_fermeture.setIcon(icone2);
        jButton_fermeture.setVerticalTextPosition(SwingConstants.BOTTOM);
        jButton_fermeture.setHorizontalTextPosition(SwingConstants.CENTER);
        ImageIcon icone3 = new ImageIcon("src/image/dossier.png");
        java.awt.Image img3 = icone3.getImage();
        icone3 = new ImageIcon(img3);
        jButton_archives.setIcon(icone3);
        jButton_archives.setVerticalTextPosition(SwingConstants.BOTTOM);
        jButton_archives.setHorizontalTextPosition(SwingConstants.CENTER);
        ImageIcon icone4 = new ImageIcon("src/image/rdv.png");
        java.awt.Image img4 = icone4.getImage();
        icone4 = new ImageIcon(img4);
        jButton_prendreRDV.setIcon(icone4);
        jButton_prendreRDV.setVerticalTextPosition(SwingConstants.BOTTOM);
        jButton_prendreRDV.setHorizontalTextPosition(SwingConstants.CENTER);

        //localisation
        entetesL = new Vector();
        entetesL.add("Service");
        entetesL.add("Service géographique");
        entetesL.add("Chambre");
        entetesL.add("Lit");
        localisation = new Vector();
        Vector localisation1 = new Vector();
        localisation1.add(dpi.getdMA().getLocalisation().getService_responsable().toString());
        localisation1.add(dpi.getdMA().getLocalisation().getService_geographique().toString());
        localisation1.add(dpi.getdMA().getLocalisation().getNchambre());
        localisation1.add(dpi.getdMA().getLocalisation().getLit());
        localisation.add(localisation1);
        TableModel tableModelL = new DefaultTableModel(localisation, entetesL);
        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(tableModelL);

        //calendrier
        LocalDate current_date = LocalDate.now();
        int current_Year = current_date.getYear();
        int current_month = current_date.getMonthValue();
        List<RendezVous> rdvs = dpi.getdMA().getRendezVous();
        Calendrier calendrier = new Calendrier(20, 50, current_month, current_Year, jPanel_rendezvous, rdvs);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Panel_Bandeau = new javax.swing.JPanel();
        Panel_logo = new javax.swing.JLabel();
        Panel_icon_perso1 = new javax.swing.JLabel();
        prenom_SA = new javax.swing.JLabel();
        nom_SA = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        Panle_Gauche = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel_telephone = new javax.swing.JLabel();
        jLabel_medecin = new javax.swing.JLabel();
        jLabel_adresse = new javax.swing.JLabel();
        Label_Icon_Patient = new javax.swing.JLabel();
        jPanel_rendezvous = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_modifier = new javax.swing.JButton();
        jButton_fermeture = new javax.swing.JButton();
        jButton_archives = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton_prendreRDV = new javax.swing.JButton();

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("date");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Connexa");
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        Panel_Bandeau.setBackground(new java.awt.Color(213, 123, 213));
        Panel_Bandeau.setRequestFocusEnabled(false);

        Panel_logo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Panel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo connexa-modified.png"))); // NOI18N

        Panel_icon_perso1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profil 2.png"))); // NOI18N

        prenom_SA.setText("prenomSA");

        nom_SA.setText("nomSA");

        jButton2.setBackground(new java.awt.Color(204, 102, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/se-deconnecter.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(204, 102, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_BandeauLayout = new javax.swing.GroupLayout(Panel_Bandeau);
        Panel_Bandeau.setLayout(Panel_BandeauLayout);
        Panel_BandeauLayout.setHorizontalGroup(
            Panel_BandeauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_BandeauLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_BandeauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(Panel_icon_perso1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_BandeauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(prenom_SA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nom_SA, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Panel_logo)
                .addContainerGap())
        );
        Panel_BandeauLayout.setVerticalGroup(
            Panel_BandeauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_icon_perso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Panel_BandeauLayout.createSequentialGroup()
                .addGroup(Panel_BandeauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_BandeauLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Panel_logo))
                    .addGroup(Panel_BandeauLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_BandeauLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(prenom_SA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nom_SA)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panle_Gauche.setBackground(new java.awt.Color(250, 247, 247));
        Panle_Gauche.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Panle_Gauche.setAutoscrolls(true);

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel6.setText("Nom :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel7.setText("Prénom :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel8.setText("Sexe :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel9.setText("Date de naissance :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("nom");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("prenom");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("sexe");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("date");

        jLabel15.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel15.setText("Téléphone :");

        jLabel16.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel16.setText("Adresse :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel14.setText("Médecin traitant :");

        jLabel_telephone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_telephone.setText("téléphone");

        jLabel_medecin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_medecin.setText("medecin");

        jLabel_adresse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_adresse.setText("adresse");

        Label_Icon_Patient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profil.png"))); // NOI18N

        javax.swing.GroupLayout Panle_GaucheLayout = new javax.swing.GroupLayout(Panle_Gauche);
        Panle_Gauche.setLayout(Panle_GaucheLayout);
        Panle_GaucheLayout.setHorizontalGroup(
            Panle_GaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panle_GaucheLayout.createSequentialGroup()
                .addGroup(Panle_GaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panle_GaucheLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Panle_GaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panle_GaucheLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Label_Icon_Patient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(Panle_GaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(Panle_GaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_medecin, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119))
        );
        Panle_GaucheLayout.setVerticalGroup(
            Panle_GaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panle_GaucheLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(Panle_GaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Panle_GaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panle_GaucheLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(Panle_GaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addGap(11, 11, 11)
                        .addGroup(Panle_GaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panle_GaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panle_GaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panle_GaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel_adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panle_GaucheLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Label_Icon_Patient)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panle_GaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel_medecin, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_rendezvous.setBackground(new java.awt.Color(169, 206, 243));

        javax.swing.GroupLayout jPanel_rendezvousLayout = new javax.swing.GroupLayout(jPanel_rendezvous);
        jPanel_rendezvous.setLayout(jPanel_rendezvousLayout);
        jPanel_rendezvousLayout.setHorizontalGroup(
            jPanel_rendezvousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );
        jPanel_rendezvousLayout.setVerticalGroup(
            jPanel_rendezvousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Service", "Service géographique ", "Chambre "
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jTable1.setEnabled(false);
        jTable1.setPreferredSize(new java.awt.Dimension(225, 27));
        jScrollPane1.setViewportView(jTable1);

        jButton_modifier.setBackground(new java.awt.Color(204, 204, 255));
        jButton_modifier.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        jButton_modifier.setText("Modifier le patient");

        jButton_fermeture.setBackground(new java.awt.Color(204, 204, 255));
        jButton_fermeture.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        jButton_fermeture.setText("Fermer le dossier");

        jButton_archives.setBackground(new java.awt.Color(204, 204, 255));
        jButton_archives.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        jButton_archives.setText("Envoyer aux archives");

        jPanel2.setBackground(new java.awt.Color(169, 206, 243));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/calendrier.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Prochain rendez-vous :");

        jTextPane1.setBackground(new java.awt.Color(169, 206, 243));
        jTextPane1.setEnabled(false);
        jScrollPane3.setViewportView(jTextPane1);

        jButton_prendreRDV.setBackground(new java.awt.Color(169, 206, 243));
        jButton_prendreRDV.setFont(new java.awt.Font("Lucida Console", 0, 11)); // NOI18N
        jButton_prendreRDV.setText("Prendre rendez-vous");
        jButton_prendreRDV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton_prendreRDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_prendreRDVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton_prendreRDV))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jButton_prendreRDV, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Bandeau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_fermeture, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_archives, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Panle_Gauche, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_rendezvous, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Panel_Bandeau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Panle_Gauche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton_modifier, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(jButton_archives, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_fermeture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel_rendezvous, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        /*Connexion i;
        try {
            i = new Connexion(conn);
            i.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Accueil_Med.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Accueil_Med.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        /*Connexion i;
        try {
            i = new Accueil_Med(conn);
            i.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Accueil_Med.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Accueil_Med.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton_prendreRDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_prendreRDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_prendreRDVActionPerformed

    class Calendrier extends JPanel implements ActionListener {

        JPanel container;
        Vector btnVect = new Vector();
        SButton suiv;
        SButton prec;
        List<RendezVous> rdvs;

        int x0, y0, mois, annee;//x0 et y0 sont les coordonnées pour setLocation 

        Calendrier(int x0, int y0, int iMois, int iAnnee, JPanel container, List<RendezVous> rdvs) {
            super();
            this.container = container;
            this.x0 = x0;
            this.y0 = y0;
            this.mois = iMois;
            this.annee = iAnnee;
            this.rdvs = rdvs;
            container.setLayout(null);
            setOpaque(false); //si vous utiliser une image comme fond 
            setBounds(x0, y0, 420, 360);
            setLayout(null);
            container.add(this);

            prec = new SButton("<<", 100, 0, 50, 28, true, this);
            new SLabel(string(iMois) + " " + iAnnee, 1, 14, 150, 0, 120, 30, this);
            suiv = new SButton(">>", 270, 0, 50, 28, true, this);
            prec.addActionListener(this);
            suiv.addActionListener(this);

            new SLabel("Lun", 1, 12, 60, 30, 60, 30, this);
            new SLabel("Mar", 1, 12, 120, 30, 60, 30, this);
            new SLabel("Mer", 1, 12, 180, 30, 60, 30, this);
            new SLabel("Jeu", 1, 12, 240, 30, 60, 30, this);
            new SLabel("Ven", 1, 12, 300, 30, 60, 30, this);
            new SLabel("Sam", 1, 12, 360, 30, 60, 30, this);
            new SLabel("Dim", 1, 12, 0, 30, 60, 30, this);

            remplirVect();
            afficherGrille(iMois, iAnnee, rdvs);
        }

        //procedure de remplissage du vecteur par des boutton standard 
        public void remplirVect() {
            int ligne = 0;
            while (ligne < 6) {
                int colonne = 0;
                while (colonne < 7) {
                    JButton btn = new JButton();
                    btn.setBounds(colonne * 60, (ligne * 60) + 60, 60, 60);
                    btn.setVisible(false);
                    btnVect.addElement(btn);
                    colonne++;
                }
                ligne++;
            }
        }

        public void afficherGrille(int iMois, int iAnnee, List<RendezVous> rdvs) {
            for (int i = jour(iAnnee, iMois, 1); i < (jour(iAnnee, iMois, 1) + nbreJour(iMois, iAnnee)); i++) {
                JButton b = new JButton();
                b = (JButton) btnVect.elementAt(i - 1);

                for (int j = 0; j < rdvs.size(); j++) {
                    RendezVous rdv = rdvs.get(j);
                    DateHeure dh = rdv.getDateHeure();
                    if (dh.getAnnee() == iAnnee && dh.getMois() == iMois && dh.getJour() == i) {
                        if(estApresDateCourante(dh.getAnnee(),dh.getMois(),dh.getJour(),dh.getHeure(),dh.getMinutes())){
                            b.setBackground(Color.BLUE);
                        }else{
                            b.setBackground(Color.ORANGE);
                        }
                        b.addMouseListener(new java.awt.event.MouseAdapter() {
                            @Override
                            public void mouseClicked(java.awt.event.MouseEvent evt) {
                                String ch = "Rendez-vous \n\nLe " + dh.getJour() + "/" + dh.getMois() + "/" + dh.getAnnee();
                                ch = ch + "\nA " + dh.getHeure() + ":" + dh.getMinutes();
                                ch = ch + "\nAvec ";
                                ch = ch + rdv.getpH().toString();
                                JOptionPane.showMessageDialog(jPanel1, ch, "Détails du rendez-vous", JOptionPane.INFORMATION_MESSAGE);

                            }
                        });
                    }
                }

                b.setVisible(true);
                b.setLabel(new Integer(i - jour(iAnnee, iMois, 1) + 1).toString());
                add(b);
                b.addActionListener(this);
            }
        }

        public int jour(int annee, int mois, int jour) {
            int retour = 0;
            for (int i = 1900; i < annee; i++) {
                if (i % 4 == 0) {
                    retour += 366;
                } else {
                    retour += 365;
                }
            }
            for (int i = 1; i < mois; i++) {
                if ((i == 1) || (i == 3) || (i == 5) || (i == 7) || (i == 8) || (i == 10) || (i == 12)) {
                    retour += 31;
                }
                if ((i == 4) || (i == 6) || (i == 9) || (i == 11)) {
                    retour += 30;
                }
                if ((i == 2) && (annee % 4 == 0)) {
                    retour += 29;
                }
                if ((i == 2) && (annee % 4 != 0)) {
                    retour += 28;
                }
            }
            for (int i = 0; i < jour; i++) {
                retour += 1;
            }
            if (retour % 7 == 0) {
                retour = 7;
            } else {
                retour = retour % 7;
            }
            return (retour);
        }

        public String string(int i) {
            String retour = new String();

            switch (i) {
                case 1: {
                    retour = "Janvier";
                    break;
                }
                case 2: {
                    retour = "Février";
                    break;
                }
                case 3: {
                    retour = "Mars";
                    break;
                }
                case 4: {
                    retour = "Avril";
                    break;
                }
                case 5: {
                    retour = "Mai";
                    break;
                }
                case 6: {
                    retour = "Juin";
                    break;
                }
                case 7: {
                    retour = "Juillet";
                    break;
                }
                case 8: {
                    retour = "Aout";
                    break;
                }
                case 9: {
                    retour = "Septembre";
                    break;
                }
                case 10: {
                    retour = "Octobre";
                    break;
                }
                case 11: {
                    retour = "Novembre";
                    break;
                }
                case 12: {
                    retour = "Décembre";
                    break;
                }
            }
            return retour;
        }

        public int nbreJour(int mois, int annee) {
            int retour = 0;

            switch (mois) {
                case 1: {
                    retour = 31;
                    break;
                }
                case 2: {
                    if (annee % 4 == 0) {
                        retour = 29;
                    } else {
                        retour = 28;
                    }
                    break;
                }
                case 3: {
                    retour = 31;
                    break;
                }
                case 4: {
                    retour = 30;
                    break;
                }
                case 5: {
                    retour = 31;
                    break;
                }
                case 6: {
                    retour = 30;
                    break;
                }
                case 7: {
                    retour = 31;
                    break;
                }
                case 8: {
                    retour = 31;
                    break;
                }
                case 9: {
                    retour = 30;
                    break;
                }
                case 10: {
                    retour = 31;
                    break;
                }
                case 11: {
                    retour = 30;
                    break;
                }
                case 12: {
                    retour = 31;
                    break;
                }
            }
            return retour;
        }

        public void actionPerformed(ActionEvent e) {
            if (e.getSource() == suiv) {
                container.removeAll();
                container.repaint();
                int m, a;
                if (mois == 12) {
                    m = 1;
                    a = annee + 1;
                } else {
                    m = mois + 1;
                    a = annee;
                }
                container.add(new Calendrier(x0, y0, m, a, container, rdvs));
                container.repaint();
            }
            if (e.getSource() == prec) {
                container.removeAll();
                container.repaint();
                int m, a;
                if (mois == 1) {
                    m = 12;
                    a = annee - 1;
                } else {
                    m = mois - 1;
                    a = annee;
                }
                container.add(new Calendrier(x0, y0, m, a, container, rdvs));
                container.repaint();
            }
        }

        public boolean estApresDateCourante(int annee, int mois, int jour, int heure, int minutes) {
            LocalDate current_date = LocalDate.now();
            LocalTime current_time = LocalTime.now();
            if (annee < current_date.getYear()) {
                return false;
            } else if (annee > current_date.getYear()) {
                return true;
            } else if (mois < current_date.getMonthValue()) {
                return false;
            } else if (mois > current_date.getMonthValue()) {
                return true;
            } else if (jour < current_date.getDayOfMonth()) {
                return false;
            } else if (jour > current_date.getDayOfMonth()) {
                return true;
            } else if (heure < current_time.getHour()) {
                return false;
            } else if (heure > current_time.getHour()) {
                return true;
            } else if (minutes < current_time.getMinute()) {
                return false;
            } else if (minutes > current_time.getMinute()) {
                return true;
            }
            return true;

        }

    }

// les deux classes qui suivent font partie de ma biblioth�que de composants person�lis�e 
// changer les si elles vous plaisent pa ;) 
//****************************************************************/ 
//label personalis� 
    /**
     * *************************************************************
     */
    class SLabel extends JLabel {

        public SLabel(String label, int horizental, int taillePolice, int x0, int y0, int x, int y, JPanel contentPane) {
            super(label);
            setFont(new java.awt.Font("Monospaced", 1, taillePolice));
            setBounds(x0, y0, x, y);
            if (horizental == 0) {
                setHorizontalAlignment(SwingConstants.LEFT);
            }
            if (horizental == 1) {
                setHorizontalAlignment(SwingConstants.CENTER);
            }
            if (horizental == 2) {
                setHorizontalAlignment(SwingConstants.RIGHT);
            }
            contentPane.add(this);

        }
    }

    /**
     * *************************************************************
     */
// Boutons personalis� 
    /**
     * ************************************************************
     */
    class SButton extends JButton {

        public SButton(String label, int x0, int y0, int x, int y, boolean visible, JPanel contentPane) {
            super(label);
            setFont(new java.awt.Font("Monospaced", 1, 14));
            setBounds(x0, y0, x, y);
            setVisible(visible);
            setOpaque(false);
            contentPane.add(this);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Infirmier inf1 = new Infirmier("3587492736", "Lo", "Anna", Service.Biologie_clinique, "momodepasse");
                PH ph1 = new PH("1616161616", "Pan", "Peter", Service.Biologie_clinique, "peterpan", "0456486756", "Biologie");

                Acte a11 = new Acte("prise de sang", nf.Type.diagnostic, Code.CS, 2, "RAS");
                Acte a12 = new Acte("changement pansement", nf.Type.therapeutique, Code.FP, 1, "Propre");
                DateHeure d11 = new DateHeure(2022, 02, 10, 10, 00); //date Fiche de soins
                FicheDeSoins fs1 = new FicheDeSoins(d11);
                fs1.setpH(ph1);
                fs1.ajouterActe(a11);
                fs1.ajouterActe(a12);
                DateHeure d12 = new DateHeure(2022, 02, 10, 11, 00); //date presciption
                Prescription p1 = new Prescription(d12, "a prendre 2 fois par jour pendant 7 jours", null, "Doliprane");
                p1.setpH(ph1);
                DateHeure d13 = new DateHeure(2022, 02, 10, 14, 00); //date de sortie
                LettreDeSortie ls1 = new LettreDeSortie("Madame ... sort de l'hopital", d13);
                ls1.setPh(ph1);
                DateHeure d14 = new DateHeure(2022, 02, 10, 10, 30); //date de soin quotidien
                DateHeure d15 = new DateHeure(2022, 02, 10, 8, 30); //date de soin quotidien
                SoinsQuotidien sq1 = new SoinsQuotidien(37.5, 80, 12.8, "RSA", d14);
                SoinsQuotidien sq2 = new SoinsQuotidien(37.0, 80, 12.9, "RSA", d15);
                sq1.setInfirmier(inf1);
                sq2.setInfirmier(inf1);
                DateHeure d16 = new DateHeure(2022, 02, 10, 11, 30); //date de l'examen
                Examen e1 = new Examen(TypeExamen.biopsie, "cancer trouvé", d16);
                e1.setPh(ph1);
                DM dm1 = new DM();
                dm1.ajouterFicheDeSoins(fs1);
                dm1.ajouterLettreDeSortie(ls1);
                dm1.ajouterPrescription(p1);
                dm1.ajouterSoinsQuotidien(sq1);
                dm1.ajouterSoinsQuotidien(sq2);
                dm1.ajouterExamen(e1);
                Localisation l1 = new Localisation(Service.Biologie_clinique, Lit.F, 12, Service.Addictologie);
                DMA dma1 = new DMA(l1);
                dma1.ajouterFicheDeSoins(fs1);
                dma1.ajouterLettreDeSortie(ls1);
                dma1.ajouterExamen(e1);
                DateHeure d17 = new DateHeure(2022, 02, 15, 10, 00); //date de RDV
                RendezVous rdv1 = new RendezVous(d17, "reverifier les resultats");
                DateHeure d18 = new DateHeure(2022, 03, 28, 9, 00); //date de RDV
                RendezVous rdv2 = new RendezVous(d18, "refaire des tests");
                rdv1.setpH(ph1);
                rdv2.setpH(ph1);
                dma1.ajouterRendezVous(rdv1);
                dma1.ajouterRendezVous(rdv2);
                MedecinTraitant mt1 = new MedecinTraitant("id@gmail.com", "PAT", "PATROUILLE", "0467894567");
                Date dn1 = new Date(1997, 07, 13); //date de naissance
                DPI dpi1 = new DPI("1234567891", "Jones", "Jack", dn1, Sexe.homme, "3 rue Beranger, 45000 Tours", "0657985613", mt1, dma1, dm1);

                inf1.ajouterSoinsQuotidien(sq1);
                inf1.ajouterSoinsQuotidien(sq2);
                ph1.ajouterFicheDeSoins(fs1);
                ph1.ajouterLettresDeSorties(ls1);
                ph1.ajouterPrescriptions(p1);
                ph1.ajouterExamen(e1);
                ph1.ajouterRdv(rdv1);
                ph1.ajouterRdv(rdv2);
                sq1.setDPI(dpi1);
                sq2.setDPI(dpi1);
                fs1.setDPI(dpi1);
                ls1.setDPI(dpi1);
                p1.setDPI(dpi1);
                e1.setDPI(dpi1);
                rdv1.setDPI(dpi1);
                rdv2.setDPI(dpi1);

                SecretaireAdministrative sa = new SecretaireAdministrative("5678452345", "Blabla", "car", "car");
                new Vue_Patient_SA(dpi1, sa).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Icon_Patient;
    private javax.swing.JPanel Panel_Bandeau;
    private javax.swing.JLabel Panel_icon_perso1;
    private javax.swing.JLabel Panel_logo;
    private javax.swing.JPanel Panle_Gauche;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton_archives;
    private javax.swing.JButton jButton_fermeture;
    private javax.swing.JButton jButton_modifier;
    private javax.swing.JButton jButton_prendreRDV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_adresse;
    private javax.swing.JLabel jLabel_medecin;
    private javax.swing.JLabel jLabel_telephone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_rendezvous;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel nom_SA;
    private javax.swing.JLabel prenom_SA;
    // End of variables declaration//GEN-END:variables

}
