package nf;

public enum Service {
    Addictologie,
    AMP,
    Gynécologie_et_obstétrique,
    Anesthésie,
    Biologie_clinique,
    Cardiologie_et_Cardiologie_interventionnelle,
    Centre_d_Étude_et_de_Traitement_de_la_Douleur,
    Chirurgie_digestive,
    Chirurgie_thoracique_et_transplantation_pulmonaire,
    Chirurgie_vasculaire,
    Diabétologie_et_Endocrinologie,
    Endoscopie_digestive,
    Gériatrie_aiguë,
    Médecine_interne,
    Médecine_nucléaire,
    Médecine_physique_et_réadaptation,
    Néphrologie,
    Neurochirurgie,
    Neurologie,
    Neuroradiologie_thérapeutique_et_interventionnelle,
    Oncologie_et_soins_de_supports,
    Ophtalmologie,
    ORL_et_chirurgie_cervico_faciale,
    Pharmacie,
    Psychiatrie,
    Radiologie,
    Réanimation_polyvalente,
    Réseau_Ville_Hôpital,
    Service_de_pneumologie,
    Stomatologie_Laboratoire_de_prothèses,
    Unité_de_soins_intensifs_respiratoires,
    Urgences,
    Urologie 
}
