package nf;

public enum Service {
    Addictologie,
    AMP,
    Gynecologie_et_obstetrique,
    Anesthesie,
    Biologie_clinique,
    Cardiologie_et_Cardiologie_interventionnelle,
    Centre_d_Etude_et_de_Traitement_de_la_Douleur,
    Chirurgie_digestive,
    Chirurgie_thoracique_et_transplantation_pulmonaire,
    Chirurgie_vasculaire,
    Diabetologie_et_Endocrinologie,
    Endoscopie_digestive,
    Geriatrie_aigue,
    Medecine_interne,
    Medecine_nucleaire,
    Medecine_physique_et_readaptation,
    Nephrologie,
    Neurochirurgie,
    Neurologie,
    Neuroradiologie_therapeutique_et_interventionnelle,
    Oncologie_et_soins_de_supports,
    Ophtalmologie,
    ORL_et_chirurgie_cervico_faciale,
    Pharmacie,
    Psychiatrie,
    Radiologie,
    Reanimation_polyvalente,
    Reseau_Ville_Hopital,
    Service_de_pneumologie,
    Stomatologie_Laboratoire_de_protheses,
    Unite_de_soins_intensifs_respiratoires,
    Urgences,
    Urologie
}
