package nf;

public enum TypeExamen {
    respiratoire,
    reflexes,
    examen_vue,
    ophtalmoscopie,
    ouie,
    toucher_rectal,
    vagin_col_uterus,
    biopsie,
    ponction_lombaire,
    examens_sanguins, 
    urinaire,
    ADN_ARN,
    analyse_selles,
    gaz_sanguins,
    microbiologie,
    radiologie,
    ultrasons,
    electrocardiographie,
    electroencephalographie,
    scanner,
    tomographie_a_emission_de_positron,
    imagerie_par_resonance_magnetique,
    coloscopie,
    cystoscopie,
    sigmoidoscopie,
    hysteroscopie,
    coelioscopie,
    colposcopie,
    plethysmographie
}
