package projetsis;

public enum TypeExamen {
    respiratoire,
    réflexes,
    examen_vue,
    ophtalmoscopie,
    ouïe,
    toucher_rectal,
    vagin_col_utérus,
    biopsie,
    ponction_lombaire,
    examens_sanguins, 
    urinaire,
    ADN_ARN,
    analyse_selles,
    gaz_sanguins,
    microbiologie,
    radiologie,
    ultrasons,
    électrocardiographie,
    électroencéphalographie,
    scanner,
    tomographie_à_émission_de_positron,
    imagerie_par_résonance_magnétique,
    coloscopie,
    cystoscopie,
    sigmoïdoscopie,
    hystéroscopie,
    cœlioscopie,
    colposcopie,
    pléthysmographie
}
